import type { View } from './store-context'

/**
 * Addresses.
 *
 * Until now the product had exactly one URL. Every reload landed on the
 * assessment sheet, the browser's back button left the application entirely,
 * and there was no way to say "look at the risk register on this one" other
 * than describing the clicks. For a tool people are meant to reason with
 * together, being unaddressable is a real defect, not a missing nicety.
 *
 * Routing lives in the fragment rather than the path. That is not a shortcut:
 * this is a static, local-first application with no server to rewrite paths,
 * and a fragment is also the only part of a URL browsers never transmit — which
 * is what makes a shared assessment (`#/s/<token>`) possible without anyone
 * hosting it.
 *
 * These functions are pure and total. Anything unrecognised resolves to the
 * assessment sheet rather than an error page.
 */

export const DEEP_TABS = [
  { id: 'controls', label: 'Controls & pattern' },
  { id: 'capacity', label: 'Economics' },
  { id: 'stress', label: 'Stress test' },
  { id: 'risk', label: 'Risk register' },
  { id: 'plan', label: 'Plan' },
  { id: 'decision', label: 'Decision' },
] as const

export type DeepTab = (typeof DEEP_TABS)[number]['id']

export const DEFAULT_TAB: DeepTab = 'controls'

const TAB_IDS: readonly string[] = DEEP_TABS.map((t) => t.id)

function isTab(value: string | undefined): value is DeepTab {
  return value !== undefined && TAB_IDS.includes(value)
}

export type Route =
  /** The assessment sheet. `id` null means whatever is currently open. */
  | { kind: 'workspace'; id: string | null; tab: DeepTab }
  | { kind: 'library' }
  | { kind: 'compare'; ids: string[] }
  | { kind: 'method' }
  | { kind: 'brief' }
  /** An assessment carried in the link itself, opened on a chosen panel. */
  | { kind: 'shared'; token: string; tab: DeepTab }

export const HOME: Route = { kind: 'workspace', id: null, tab: DEFAULT_TAB }

/** Ids are generated by `crypto.randomUUID` or a timestamp fallback. */
const ID = /^[A-Za-z0-9_-]{1,64}$/

/**
 * Parse a location hash. Never throws; unknown shapes resolve to the sheet, on
 * the principle that a stale bookmark should open the product rather than an
 * apology.
 */
export function parseRoute(hash: string): Route {
  const raw = hash.startsWith('#') ? hash.slice(1) : hash
  const path = raw.startsWith('/') ? raw.slice(1) : raw
  if (path === '') return HOME

  const parts = path.split('/').filter(Boolean)
  const head = parts[0]

  switch (head) {
    case 'assessments':
      return { kind: 'library' }
    case 'method':
      return { kind: 'method' }
    case 'brief':
      return { kind: 'brief' }
    case 'compare': {
      const ids = decodeURIComponent(parts[1] ?? '')
        .split(',')
        .map((s) => s.trim())
        .filter((s) => ID.test(s))
        .slice(0, 4)
      return { kind: 'compare', ids }
    }
    case 's': {
      // base64url contains no slash, so a third segment can only be the panel
      // to open on. Anything else after the token is treated as part of it,
      // which keeps a link mangled in transit failing loudly at the decoder
      // rather than quietly opening the wrong assessment.
      const tail = parts[2]
      const token = isTab(tail) ? (parts[1] ?? '') : parts.slice(1).join('/')
      if (!token) return HOME
      return { kind: 'shared', token, tab: isTab(tail) ? tail : DEFAULT_TAB }
    }
    case 'a': {
      const id = parts[1] ?? ''
      if (!ID.test(id)) return HOME
      const tab = parts[2]
      return { kind: 'workspace', id, tab: isTab(tab) ? tab : DEFAULT_TAB }
    }
    case 't': {
      // A tab on whatever is open, for an assessment that has never been saved.
      const tab = parts[1]
      return { kind: 'workspace', id: null, tab: isTab(tab) ? tab : DEFAULT_TAB }
    }
    default:
      return HOME
  }
}

/** Render a route as a hash, including the leading `#`. */
export function formatRoute(route: Route): string {
  switch (route.kind) {
    case 'library':
      return '#/assessments'
    case 'method':
      return '#/method'
    case 'brief':
      return '#/brief'
    case 'compare':
      return route.ids.length > 0 ? `#/compare/${route.ids.join(',')}` : '#/compare'
    case 'shared':
      return route.tab === DEFAULT_TAB ? `#/s/${route.token}` : `#/s/${route.token}/${route.tab}`
    case 'workspace': {
      const tail = route.tab === DEFAULT_TAB ? '' : `/${route.tab}`
      if (route.id) return `#/a/${route.id}${tail}`
      return tail ? `#/t${tail}` : '#/'
    }
  }
}

/**
 * The address of the current application state.
 *
 * A never-saved assessment has an id, but it is not addressable — nobody else
 * can resolve it — so the sheet stays at `#/` until the record exists on the
 * device. Writing an id that resolves to nothing would be worse than writing
 * none at all.
 */
export function routeFor(state: {
  view: View
  currentId: string
  isSaved: boolean
  tab: DeepTab
  compareIds: string[]
}): Route {
  switch (state.view) {
    case 'library':
      return { kind: 'library' }
    case 'method':
      return { kind: 'method' }
    case 'brief':
      return { kind: 'brief' }
    case 'compare':
      return { kind: 'compare', ids: state.compareIds }
    case 'workspace':
      return {
        kind: 'workspace',
        id: state.isSaved ? state.currentId : null,
        tab: state.tab,
      }
  }
}

/** The absolute URL for a route, from the page this is running on. */
export function absoluteUrl(route: Route, location: { origin: string; pathname: string }): string {
  return `${location.origin}${location.pathname}${formatRoute(route)}`
}
